#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.native.ignoreDisabledTargets=true

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

mavenCentralUsername=your_sonatype_token_username
mavenCentralPassword=your_sonatype_token_password

signing.keyId=7j3SHwtc          # GPG 公钥 ID 后 8 位
signing.password=I3YcBH:0l22Zlpra9wiAAdCwLfbYRaJE7j3SHwtc
signing.secretKeyRingFile=/Users/dxycw/.gnupg/secring.gpg
